// <auto-generated />
using CadastroFuncionariosApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadastroFuncionariosApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250613142416_SeedFuncionarios")]
    partial class SeedFuncionarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("CadastroFuncionariosApi.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cargo = "Analista",
                            Nome = "Fernanda"
                        },
                        new
                        {
                            Id = 2,
                            Cargo = "Desenvolvedor",
                            Nome = "Alexandre"
                        },
                        new
                        {
                            Id = 3,
                            Cargo = "Coordenador",
                            Nome = "Tiago"
                        },
                        new
                        {
                            Id = 4,
                            Cargo = "TI",
                            Nome = "Marcelo"
                        },
                        new
                        {
                            Id = 5,
                            Cargo = "RH",
                            Nome = "Bernadete"
                        },
                        new
                        {
                            Id = 6,
                            Cargo = "Financeiro",
                            Nome = "Fabrício"
                        },
                        new
                        {
                            Id = 7,
                            Cargo = "Suporte",
                            Nome = "Diogo"
                        },
                        new
                        {
                            Id = 8,
                            Cargo = "Comercial",
                            Nome = "Jéssica"
                        },
                        new
                        {
                            Id = 9,
                            Cargo = "Marketing",
                            Nome = "Karoline"
                        },
                        new
                        {
                            Id = 10,
                            Cargo = "Administrativo",
                            Nome = "Jaqueline"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
